#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# <<<xsan_paths>>>
#
# Controller: <default>
#     VOLUME     on device: rdisk18      hba: 1 ctl: 0 lun: 1 state: Available


def inventory_cvadmin_paths(checkname, info):
    inventory = []
    for line in info:
    	params = {}
    	params["state"] = list_get_next(line, "state:")
    	inventory.append( (line[0], params) )
    return inventory


def check_cvadmin_paths(item, params, info):
    for line in info:
    	if line[0] == item:
			infotext = [list_get_next(line, "device:")]
			worst_state = 0
			state = list_get_next(line, "state:")
			lun = list_get_next(line, "lun:")
			ctl = list_get_next(line, "ctl:")
			hba = list_get_next(line, "hba:")

			if state != params["state"]:
				infotext.append( "Expected %s State" % params["state"] )
				infotext[-1] += "(!!)"
				worst_state = max(worst_state, 2)
			infotext.append( "Current State %s" % state  )
			infotext.append( "HBA %s" % hba )
			infotext.append( "Controller %s" % ctl )
			infotext.append( "LUN %s" % lun )

			return ( worst_state, ", ".join(infotext) )

    return 3, "Path %s not found" % item


check_info["cvadmin_paths"] = {
	'check_function':			check_cvadmin_paths,
	'inventory_function':		inventory_cvadmin_paths,
	"service_description":		"CVADMIN Path %s",
    "includes"                : [ "cvadmin.include" ],
    "group"                   : "filesystem",
}
